### ISSUE TITLE
Cannot compile on Ubuntu 21.10 (ISO C++17 does not allow dynamic exception specifications)

### ISSUE THREAD

**Issue by hellocatfood** [slowmoVideo/v3d-flow-builder#2]
Trying to compile v3d on Ubuntu 21.10 and when  I run `make` I get the following error and the compilation fails:
```
[ 63%] Built target V3D
[ 72%] Building CXX object src/CMakeFiles/slowmoFlowBuilder.dir/flowBuilder.cpp.o
In file included from ****/v3d-flow-builder/src/flowBuilder.cpp:30:
****/v3d-flow-builder/src/lib/libsvflow/src/flowRW_sV.h:71:53: error: ISO C++17 does not allow dynamic exception specifications
   71 |     static FlowField_sV* load(std::string filename) throw(FlowRWError);
      |                                                     ^~~~~
make[2]: *** [src/CMakeFiles/slowmoFlowBuilder.dir/build.make:82: src/CMakeFiles/slowmoFlowBuilder.dir/flowBuilder.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:142: src/CMakeFiles/slowmoFlowBuilder.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

**Comment by mpfaff** [comment]
Same issue on Manjaro with gcc 11.2.0-3

**Comment by Granjow** [comment]
Sorry, I currently don't have time to work on that issue – will fix it once I have time, but I'm also happy to accept PRs.

**Comment by dimonf** [comment]
Same problem.

**Comment by evertvorster** [comment]
Yup, same problem here.
I am assuming that it's the newer version of GCC not being happy with the way things were done in the past.

**Comment by evertvorster** [comment]
Heh, seems that this is not a new thing, and there is some guides on how to solve it on Stack Overflow:
https://stackoverflow.com/questions/75593159/how-to-correctly-port-dynamic-exceptions-to-c17-from-c98

**Comment by JJones780** [comment]
git submodule update --init  is not pulling down the latest commits.

**run
`git submodule update --recursive --remote`**

to get the latest head with the proper fixes.


**If that doesn't work** you can look [here](https://stackoverflow.com/questions/1030169/pull-latest-changes-for-all-git-submodules) for other things to try.

**OR** simply change 
line 68 in src/lib/libsvflow/src/flowRW_sV.cpp by removing the  `throw(FlowRWError)` so it is:
`FlowField_sV* FlowRW_sV::load(std::string filename)`
and 
line 70 in src/lib/libsvflow/include/flowRW_sV.h remove the `throw(FlowRWError)`  so it is:
static FlowField_sV* load(std::string filename) ;

**Comment by JJones780** [comment]
adding --remote to the instructions as below works too:


> ### Building
> 
> On Ubuntu 20.04, install the requirements freeglut3-dev libopencv-dev libglew-dev 
> 
> git submodule update --init --remote
> mkdir build
> cd build
> cmake ..
> make

but there are errors.. see next entry...

**Comment by JJones780** [comment]
Now there are errors finding flowField_sV.h.

These  files need to be edited to update the paths to  flowField_sV.h and flowRW_sV.h. 

 v3d-flow-builder/CMakeLists.txt
Lines 259 and 260 should be changed to read:
```
    src/lib/libsvflow/include/flowField_sV.h
    src/lib/libsvflow/include/flowRW_sV.h
```
and in  the following file the include path is wrong:
 v3d-flow-builder/src/CMakeLists.txt
line 1 should be changed to read:
`include_directories(${V3D_INCLUDE_DIRS} ${EXTRA_INC_DIRS} lib/libsvflow/include)`

and now it compiles.

I'll submit a patch.

**Comment by JJones780** [comment]
Can we close this now?

**Comment by hellocatfood** [comment]
I'll try and compile this again but sounds like it's fixed now.

**Comment by hellocatfood** [comment]
All seems to compile now, closing as fixed
